version: '3.8'
services:
  database-mysql:
    image: mysql:8.1
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: finallapp
      MYSQL_ROOT_PASSWORD: 12345678
    expose:
      - 3306

  backend:
    build:
      context: ../app/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3308
      - DB_HOST=database-mysql
    ports:
      - "8080:8080"

# then :docker compose -p az-food up -d
