import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:restaurant_manager_app/ui/theme/color_schemes.dart';

var textTheme = (BuildContext context) => TextTheme(
      titleLarge: TextStyle(
          color: colorScheme(context).scrim.withOpacity(0.8),
          letterSpacing: 0.5,
          fontWeight: FontWeight.normal,
          fontSize: 32,
          fontFamily: GoogleFonts.roboto().fontFamily),
      titleMedium: TextStyle(
          color: colorScheme(context).scrim.withOpacity(0.8),
          letterSpacing: 0.5,
          fontWeight: FontWeight.normal,
          fontSize: 26,
          fontFamily: GoogleFonts.roboto().fontFamily),
      bodyLarge: TextStyle(
          color: colorScheme(context).scrim.withOpacity(0.8),
          letterSpacing: 0.5,
          fontWeight: FontWeight.normal,
          fontSize: 18,
          fontFamily: GoogleFonts.roboto().fontFamily),
      labelLarge: TextStyle(
          color: colorScheme(context).scrim.withOpacity(0.8),
          letterSpacing: 0.5,
          fontWeight: FontWeight.normal,
          fontSize: 14,
          fontFamily: GoogleFonts.roboto().fontFamily),
      bodyMedium: TextStyle(
          color: colorScheme(context).scrim.withOpacity(0.8),
          letterSpacing: 0.5,
          fontWeight: FontWeight.normal,
          fontSize: 16,
          fontFamily: GoogleFonts.roboto().fontFamily),
      bodySmall: TextStyle(
          color: colorScheme(context).scrim.withOpacity(0.8),
          letterSpacing: 0.5,
          fontWeight: FontWeight.normal,
          fontSize: 11,
          fontFamily: GoogleFonts.roboto().fontFamily),
    );
